// This file is automatically generated. Do not edit it directly. - IntellectFlow PRO - Founder Kaushik Savaliya - Market Value ₹55k+ at ₹299
// PRO: Lifetime Free + Market Value Logging + Founder Check
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
// Founder: Kaushik Savaliya - Visavadar Gujarat - intellectflowteam@gmail.com - Market Value ₹55k+ Billing Protection
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next, context }) => {
    const { data, error } = await supabase.auth.getSession()
    const token = data.session?.access_token
    const user = data.session?.user
    
    // PRO: Logging for Market Value billing + Lifetime Free check - Value ₹55k+ Billing Security
    if (user) {
      const isFounder = user.email === 'intellectflowteam@gmail.com' || user.email?.endsWith('@intellectflow.in');
      if (isFounder) {
        console.log(`Founder Kaushik Savaliya access - Email: ${user.email} - Lifetime Free ✓ Value ₹55k+ FREE - Aap Dukaan Chalao Google Hum Sambhalenge - Market Value Billing Protected`);
      } else if (process.env.NODE_ENV === 'development') {
        console.log(`Auth token attached - User: ${user.email} - Market Value ₹55k+ Billing - Token: ${token ? 'Present' : 'Missing'}`);
      }
    } else if (error) {
      console.warn(`Supabase session error - Market Value ₹55k+ Billing - Error: ${error.message} - Founder Kaushik Savaliya`);
    }

    return next({
      headers: token ? { 
        Authorization: `Bearer ${token}`,
        'X-IntellectFlow-User': user?.email || 'anonymous',
        'X-IntellectFlow-Founder': user?.email === 'intellectflowteam@gmail.com' ? 'Kaushik Savaliya - Lifetime Free ✓ Value ₹55k+ FREE' : 'Customer - Market Value ₹55k+ at ₹299',
        'X-IntellectFlow-Market-Value': '₹55k+/mo Features at ₹299 - QR ₹1k + AI Writer ₹3k/mo + Coupon ₹1.5k/mo + Negative Filter ₹7k/mo + Reviews ₹5k/mo + AI Reply ₹5k/mo + WhatsApp ₹3k/mo + GMB ₹8k/mo + Sentiment ₹5k/mo + Competitor ₹12k/mo',
        'X-IntellectFlow-Tagline': 'Aap Dukaan Chalao, Google Hum Sambhalenge - 500+ Businesses - Founder Kaushik Savaliya - Visavadar Gujarat 362130'
      } : {
        'X-IntellectFlow-User': 'anonymous',
        'X-IntellectFlow-Market-Value': 'Public - QR Page /r/slug - Value ₹1k + ₹8k/mo - Founder Kaushik Savaliya'
      },
    })
  },
)

// PRO: Additional middleware for Lifetime Free businesses - Value ₹55k+ FREE Protection - Never block founder
export const attachLifetimeFreeCheck = createMiddleware({ type: 'function' }).server(
  async ({ next, context }: any) => {
    // This will be checked in server functions - Lifetime Free businesses never hit limits
    // Market Value ₹55k+ FREE - Founder Kaushik Approved
    const businessId = context?.businessId;
    if (businessId) {
      try {
        // Check if lifetime free - Don't enforce limits
        // This is done in individual functions (reviews, subscription etc) - Value ₹55k+ FREE logic
        console.log(`Lifetime Free check for Business: ${businessId} - Market Value ₹55k+ FREE Protection - Founder Kaushik Savaliya`);
      } catch (e) {
        console.error(`Lifetime Free check failed - Business: ${businessId} - Market Value ₹55k+ - Error:`, e);
      }
    }
    return next();
  }
)