// This file is automatically generated. Do not edit it directly. - IntellectFlow PRO - Founder Kaushik Savaliya - Market Value ₹55k+ at ₹299
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
// PRO: Lifetime Free Protection + Market Value Billing + Founder Kaushik Logging
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    // PRO: Market Value headers for tracking - Founder Kaushik Savaliya
    headers.set('X-IntellectFlow-Market-Value', '₹55k+/mo Value - Founder Kaushik - Aap Dukaan Chalao Google Hum Sambhalenge');
    headers.set('X-IntellectFlow-Founder', 'Kaushik Savaliya - Visavadar Gujarat - intellectflowteam@gmail.com');
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  // PRO: Support both SUPABASE_URL and VITE_SUPABASE_URL for Vercel deploy fix - intellection-nine.vercel.app 404 fix
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL or VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Vercel Env Vars. Founder Kaushik Savaliya - intellectflowteam@gmail.com - Market Value ₹55k+ Billing - Fix: Add SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Vercel Dashboard → Settings → Environment Variables → Redeploy.`;
    console.error(`[Supabase Admin] ${message} - Market Value ₹55k+ Billing - Founder Kaushik Savaliya - Visavadar Gujarat`);
    throw new Error(message);
  }

  console.log(`[Supabase Admin] Client created - URL: ${SUPABASE_URL.slice(0,30)}... - Service Role: Present ✓ - Market Value ₹55k+ Billing - Founder Kaushik Savaliya - Lifetime Free Protection Enabled - Aap Dukaan Chalao Google Hum Sambhalenge`);

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
// PRO: Lifetime Free Protection - Value ₹55k+ FREE - Founder Kaushik Approved - Never block lifetime free businesses
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) {
      try {
        _supabaseAdmin = createSupabaseAdminClient();
      } catch (e: any) {
        console.error(`[Supabase Admin] Failed to create client - ${e.message} - Market Value ₹55k+ Billing - Founder Kaushik - Fix Vercel Env Vars`);
        throw e;
      }
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

// PRO: Helper to check lifetime free - Value ₹55k+ FREE Protection - Founder Kaushik Savaliya - Aap Dukaan Chalao Google Hum Sambhalenge
export async function isLifetimeFreeBusiness(businessId: string): Promise<boolean> {
  try {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    const { data, error } = await _supabaseAdmin.from('businesses').select('is_lifetime_free').eq('id', businessId).single();
    if (error) {
      console.error(`Lifetime Free check failed for ${businessId}: ${error.message} - Market Value ₹55k+ FREE - Founder Kaushik`);
      return false;
    }
    const isLifetime = (data as any)?.is_lifetime_free === true;
    if (isLifetime) {
      console.log(`Lifetime Free business detected: ${businessId} - Value ₹55k+ FREE - Founder Kaushik Approved - Aap Dukaan Chalao Google Hum Sambhalenge - Never enforce limits`);
    }
    return isLifetime;
  } catch (e: any) {
    console.error(`isLifetimeFreeBusiness error: ${e.message} - Market Value ₹55k+ FREE - Founder Kaushik`);
    return false;
  }
}