// This file is automatically generated. Do not edit it directly. - IntellectFlow PRO - Founder Kaushik Savaliya - Market Value ₹55k+ at ₹299
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    // PRO: Market Value tracking headers - Founder Kaushik Savaliya - Aap Dukaan Chalao Google Hum Sambhalenge
    headers.set('X-IntellectFlow-Client', 'Browser - Market Value ₹55k+ Features - Founder Kaushik Savaliya');
    headers.set('X-IntellectFlow-Market-Value', 'QR ₹1k + AI Writer ₹3k/mo + Coupon ₹1.5k/mo + Negative Filter ₹7k/mo + Reviews ₹5k/mo + AI Reply ₹5k/mo + WhatsApp ₹3k/mo + GMB ₹8k/mo + Sentiment ₹5k/mo + Competitor ₹12k/mo = ₹55k+/mo at ₹299');
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // PRO: Vercel Deploy Fix - Supports both VITE_ and non-VITE_ env vars - intellection-nine.vercel.app 404 fix
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL_ALT || process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL / VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_ANON_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Vercel Env Vars. Founder Kaushik Savaliya - intellectflowteam@gmail.com - Market Value ₹55k+ at ₹299 - Fix: Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel Dashboard → Settings → Environment Variables → Redeploy. Visavadar Gujarat 362130 - Aap Dukaan Chalao Google Hum Sambhalenge.`;
    console.error(`[Supabase Client] ${message} - Market Value ₹55k+ - Founder Kaushik Savaliya - 500+ Businesses`);
    throw new Error(message);
  }

  console.log(`[Supabase Client] Browser client created - URL: ${SUPABASE_URL.slice(0,30)}... - Key: Present ✓ - Market Value ₹55k+ at ₹299 - Founder Kaushik Savaliya - Aap Dukaan Chalao Google Hum Sambhalenge - 500+ Businesses`);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // PRO: Auto-refresh for long dashboard sessions - Value ₹55k+ - Founder Kaushik
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// PRO: Used in all client-side queries - Reviews, Businesses, Auth - Market Value ₹55k+ Features
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (e: any) {
        console.error(`[Supabase Client] Failed to create - ${e.message} - Market Value ₹55k+ - Founder Kaushik - Fix Vercel Env Vars VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY`);
        throw e;
      }
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});

// Founder: Kaushik Savaliya - Visavadar Gujarat 362130 - intellectflowteam@gmail.com - Market Value ₹55k+ at ₹299 - Aap Dukaan Chalao Google Hum Sambhalenge - 500+ Businesses - IntellectFlow.in PRO